### PR TITLE
Clean up helper classes

### PR DESCRIPTION
**Pull request by ghost**
* Add `@FunctionalInterface` to interfaces
* Move `ShadingValidator.ensureShaded()` checks to static initializers
    * I tested this with `NBTHelper`, and `ShadingValidator.ensureShaded()` was called when I created a new instance. (~~I will test other ways of initializing the class statically.~~ See https://stackoverflow.com/a/3499322/7153764 for more information on static initialization.)
* Add final modifiers and private constructors to helper classes
* Make `NBTHelper` functions static

### CODE REVIEW

**Review by exaskye — APPROVED** [review]

**Review by falkreon — APPROVED** [review]
Looks good. Final & private constructors for helper classes that shouldn't be constructed, shadingValidator checks. Formatting looks good.

I'm a little sad it says "various changes" because it's a very focused PR on helper classes, but yes, let's get this merged.

**Comment by ghost** [comment]
Yeah, I struggled to come up with an overall commit name. I agree; `Clean up helper classes` or something similar would ~have been~ be better.

**Review by jamierocks — APPROVED** [review]

**Review by darkevilmac — COMMENTED** [review]
Should ShadingValidator checks be in resgen and any other module that doesn't have them or no? Other than that I don't see anything wrong here.

**Comment by ghost** [comment]
Currently adding more shading checks. I might need Falkreon and/or CalmBit to (re)review the PR when I'm done.

**Pull request merged**
