### PR TITLE
Changed default value of ConfigValue.category to CATEGORY_GENERAL

### PR DESCRIPTION
**Pull request by ghost**
Hi, here's the error that's printed during a second run of the Minecraft client, after a configuration file is initially created, with the default empty string as a category name:
````
[19:39:42] [Client thread/ERROR]: An exception occurred while loading config file testmod.cfg. This file will be renamed to testmod.cfg_20170611_193942.errored and a new config file will be generated.
[19:39:42] [Client thread/INFO]: [STDERR]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[19:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.String.substring(String.java:1960)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.common.config.Configuration.load(Configuration.java:930)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.common.config.Configuration.runConfiguration(Configuration.java:133)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.common.config.Configuration.<init>(Configuration.java:151)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.common.config.Configuration.<init>(Configuration.java:111)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.elytradev.concrete.config.ConcreteConfig.<init>(ConcreteConfig.java:53)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at testmod.TestModConfig.<init>(TestModConfig.java:14)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at testmod.TestMod.preInit(TestMod.java:30)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:643)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:268)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.init(Minecraft.java:478)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:387)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:118)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[19:39:42] [Client thread/INFO]: [STDERR]: 	at GradleStart.main(GradleStart.java:26)
````
What seems to be happening is that Forge tries to find the name of the category, but it can't, which causes a `StringIndexOutOfBoundsException`.

### CODE REVIEW

**Comment by darkevilmac** [comment]
@gbui I don't like not having this as a default, I will see if I can reproduce the bug and will create a fix accordingly.

**Comment by ghost** [comment]
@darkevilmac Okay, I suggest `Configuration.CATEGORY_GENERAL` (or `"general"`) as a default, but it's just a suggestion.

**Comment by darkevilmac** [comment]
That's what I'm most likely going to end up doing.

**Comment by ghost** [comment]
Why remove the license header?

**Comment by darkevilmac** [comment]
> Why remove the license header?

That wasn't intended, my local copy that I used to edit was not up to date.

**Comment by ghost** [comment]
Ah, okay.

**Review by darkevilmac — APPROVED** [review]

**Pull request merged**
