### PR TITLE
Support parameter-less and/or private Message constructors

### PR DESCRIPTION
**Pull request by ghost**
Requiring a `NetworkContext` as an argument seems redundant, since `Message`s will most likely be used only by their respective mods. For example: https://github.com/elytra/Teckle/blob/8ac0c17/src/main/java/com/elytradev/teckle/common/network/messages/AlloyFurnaceMessage.java#L39-L44

### CODE REVIEW

**Comment by exaskye** [comment]
Is this really any less clutter than the current approach?

**Comment by ghost** [comment]
**Edit:** This comment is outdated; please see the updated example below.

Honestly, it ~~would save only a few lines~~ wouldn't reduce any clutter. However, it is much cleaner than how `Message`s are currently used in Elytra mods.

For example:
````java
    public AlloyFurnaceMessage(NetworkContext ctx) {
        super(ctx);
    }

    public AlloyFurnaceMessage(TileAlloyFurnace alloyFurnace) {
        super(TeckleNetworking.NETWORK);
        this.furnacePos = alloyFurnace.getPos();
        this.cookTime = alloyFurnace.cookTime;
        this.fuelBurnTime = alloyFurnace.fuelBurnTime;
        this.currentFuelWorth = alloyFurnace.currentFuelWorth;
    }
````
vs
````java
    private AlloyFurnaceMessage() {}

    public AlloyFurnaceMessage(TileAlloyFurnace alloyFurnace) {
        this.furnacePos = alloyFurnace.getPos();
        this.cookTime = alloyFurnace.cookTime;
        this.fuelBurnTime = alloyFurnace.fuelBurnTime;
        this.currentFuelWorth = alloyFurnace.currentFuelWorth;
    }

    protected NetworkContext getNetworkContext() {
        return TeckleNetworking.NETWORK
    }
````

Granted, this change would break all mods that use `Message`s, hence I pushed this change to its own PR.

**Comment by exaskye** [comment]
Not sure if this minor of a change is worth breaking all existing Message classes.

I'll decide in a minute; currently busy.

**Comment by ghost** [comment]
If you want, I could re-add the `ctx` field as a placeholder.

Edit: On second thought, a placeholder seems to be a bad idea.

**Comment by jamierocks** [comment]
Fine as is IMO

**Comment by ghost** [comment]
Updated example:
````java
    private AlloyFurnaceMessage() {
        super(TeckleNetworking.NETWORK);
    }

    public AlloyFurnaceMessage(TileAlloyFurnace alloyFurnace) {
        this();
        this.furnacePos = alloyFurnace.getPos();
        this.cookTime = alloyFurnace.cookTime;
        this.fuelBurnTime = alloyFurnace.fuelBurnTime;
        this.currentFuelWorth = alloyFurnace.currentFuelWorth;
    }
````

**Comment by darkevilmac** [comment]
I would like this but if it breaks other mods then don't bother. It's a pretty small issue for me.

**Comment by ghost** [comment]
With the new changes, implementations of `Message` with a `NetworkContext` parameter in the constructor are still compatible.

**Review by exaskye — APPROVED** [review]

**Comment by exaskye** [comment]
(Code looks fine, still deciding if I want to merge)

**Pull request merged**
